server:
  port: 17772

im:
  webSocketPort: 2222

const:
  userInfoCacheRedisKey: userInfoCache
spring:
  cloud:
    stream:
      kafka:
        binder:
          #brokers: '34.96.156.160:9091,34.96.156.160:9092,34.96.156.160:9093'
          brokers: '172.20.10.4:9091'
          auto-create-topics: true
      bindings:
        myOutput:
          destination: netty_topic
          #content-type: text/plain  不写默认是json
        myInput:
          destination: netty_topic



  redis: # service 中使用stringRedisTemplate或者redisTemplate
    database: 0 # Redis数据库索引（默认为0）
    host: 127.0.0.1 # Redis服务器地址
    port: 6379
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0  # 连接池中的最小空闲连接
    timeout: '10000' # 连接超时时间（毫秒）
  application:
    name: NettyServer
  profiles:
    active: db
ribbon:
  ConnectTimeout: '10000' # 连接超时时间(ms)
  ReadTimeout: '10000' # 通信超时时间(ms)

feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: true
    connection-timeout: '10000'